-- V17: Script neutralizado (2026-04-19).
--
-- Historia: V17 fue el script que ELIMINO multi-tenant en la Fase 0 del
-- proyecto (2026-04-12). Dropeaba company_id de 10 tablas y renombraba
-- SUPERADMIN -> ADMIN. Cumplio su funcion en esa epoca.
--
-- El 2026-04-19 el lider exigio VOLVER a multi-tenant (N empresas
-- self-service). V10-A reintroduce la tabla companies + company_id en
-- users, third_parties y parameters. Los bloques B y C agregan
-- company_id a las ~27 entidades restantes.
--
-- DataInitializer re-ejecuta todos los scripts de db/migration/ en CADA
-- arranque. Si V17 siguiera vivo, dropearia las columnas company_id que
-- V10-A acaba de agregar (V17 corre despues por orden alfabetico:
-- V10-A < V17). Por eso V17 queda como no-op.
--
-- No se borra el archivo para no romper la numeracion lexica del loader.
-- Los datos que V17 habia copiado desde companies a parameters siguen
-- vivos y se aprovechan en V10-A (seed de la empresa default SIGCON DEMO).
SELECT 1;
