-- V9-4: Script neutralizado (2026-04-19).
--
-- Historia: V9-4 ejecuto la Fase 3 del proyecto (2026-04-14), eliminando
-- las tablas deprecadas `companies` y `company_withholding_assignments`
-- tras haber sido reemplazadas por el modelo single-tenant.
--
-- El 2026-04-19 el lider exigio VOLVER a multi-tenant (decision documentada
-- en CLAUDE.md seccion "Decision estrategica 2026-04-19"). V10-A reintroduce
-- la tabla `companies` con un schema nuevo (business_name, dv, etc).
--
-- DataInitializer re-ejecuta todos los scripts en CADA arranque. El orden
-- lexicografico hace que V9-4 corra DESPUES de V10-A (porque '1' < '9'),
-- asi que si V9-4 siguiera vivo, dropearia la tabla que V10-A acaba de
-- crear. Por eso V9-4 queda como no-op.
--
-- La tabla `company_withholding_assignments` no se vuelve a crear; su
-- reemplazo actual `system_withholding_assignments` sigue siendo el que
-- se usa. Si en el futuro se requiere retenciones por empresa, esa tabla
-- se ajustara en la etapa de datos maestros (Bloque D).
SELECT 1;
