-- V9-I: script neutralizado (2026-04-18).
--
-- Historia: V9-I se creo como primer intento de seed para los 8 modulos sin
-- permisos. Tenia dos bugs: (1) todos los codes venian con prefijo `PERM_` que
-- User.java agrega en runtime -> authorities con doble prefijo que nunca
-- coincidian con los @PreAuthorize; (2) DataInitializer re-corre todos los
-- scripts en cada arranque, asi que tras V9-K (que renombro permisos al
-- espaniol) las filas como 'Ver terceros' colisionan con el UNIQUE(name).
--
-- V9-J + V9-K reemplazan este seed con los permisos correctos en espaniol
-- (sin prefijo `PERM_` en el code) y se aplican solo una vez. Por eso V9-I
-- queda como no-op: no inserta nada, pero se mantiene el archivo para no
-- romper histories de Flyway ni cambiar la numeracion del resto de scripts.
SELECT 1;
