-- =============================================================================
-- V9-ZZO__voucher_series_config.sql
--
-- HU-CG-03A E3/E5 (Bloque X): series configurables para comprobantes contables
-- por tipo. Antes el sistema usaba prefijo fijo "JE-{anio}-{N}" sin posibilidad
-- de configurar rangos ni alertas al agotarse.
--
-- Estructura:
--   * Una fila por (company_id, voucher_type) — ej. (1, 'JE'), (1, 'AJ'), (1, 'CI')
--   * prefix: identificador legible que se antepone al numero (ej. "JE", "REV", "AJ")
--   * start_number / end_number: rango disponible (1..999999 por defecto)
--   * current_number: ultimo numero asignado en la serie
--   * alert_threshold_pct: porcentaje del rango usado a partir del cual se notifica
--     al admin. Default 80% (cuando queda 20% disponible).
--
-- Multi-tenant via company_id NOT NULL. Auto-provision: cada empresa nueva
-- recibe una serie default 'JE' con rango 1..999999.
--
-- Idempotente: CREATE TABLE IF NOT EXISTS + WHERE NOT EXISTS en seeds.
-- =============================================================================

CREATE TABLE IF NOT EXISTS voucher_series_config (
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id            BIGINT NOT NULL,
    voucher_type          VARCHAR(20) NOT NULL,
    prefix                VARCHAR(20) NOT NULL,
    start_number          BIGINT NOT NULL DEFAULT 1,
    end_number            BIGINT NOT NULL DEFAULT 999999,
    current_number        BIGINT NOT NULL DEFAULT 0,
    alert_threshold_pct   INT NOT NULL DEFAULT 80,
    description           VARCHAR(255),
    status                VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at            TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at            TIMESTAMP NULL,
    CONSTRAINT ck_vsc_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'EXHAUSTED')),
    CONSTRAINT ck_vsc_threshold CHECK (alert_threshold_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_vsc_range CHECK (start_number > 0 AND end_number >= start_number)
);

-- UNIQUE compuesto por (company_id, voucher_type) para que cada empresa pueda
-- definir una serie por tipo de comprobante sin colisionar con otras empresas.
CREATE UNIQUE INDEX IF NOT EXISTS uk_vsc_company_type_active
    ON voucher_series_config (company_id, voucher_type)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_vsc_company
    ON voucher_series_config (company_id);

-- Menu de admin para series (HU-CG-03A E3/E5).
-- Solo lo agregamos si el modulo Contabilidad General (id=8) existe.
INSERT INTO menus (label, path, component, icon, module_id, menu_order, status, created_at, updated_at)
SELECT 'Series de Consecutivos', 'series', 'CG_SERIES', 'ri-list-ordered', 8, 7, 'ACTIVE', NOW(), NOW()
 WHERE EXISTS (SELECT 1 FROM modules WHERE id=8 AND deleted_at IS NULL)
   AND NOT EXISTS (SELECT 1 FROM menus WHERE component='CG_SERIES' AND deleted_at IS NULL);

-- Seed: cada empresa activa recibe una serie default 'JE' (Comprobante General)
-- con rango 1..999999 y current_number = max(entry_number) actual de la empresa
-- para no romper consecutivos existentes.
DO $$
DECLARE
    v_company_id BIGINT;
    v_max_entry BIGINT;
BEGIN
    FOR v_company_id IN
        SELECT id FROM companies WHERE deleted_at IS NULL AND status = 'ACTIVE'
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM voucher_series_config
             WHERE company_id = v_company_id AND voucher_type = 'JE' AND deleted_at IS NULL
        ) THEN
            -- Recuperar el ultimo entry_number usado por la empresa para no sobreescribir
            -- consecutivos validos. Si no hay JE, current_number = 0.
            SELECT COALESCE(MAX(entry_number), 0) INTO v_max_entry
              FROM journal_entries
             WHERE company_id = v_company_id AND deleted_at IS NULL;

            INSERT INTO voucher_series_config (
                company_id, voucher_type, prefix,
                start_number, end_number, current_number,
                alert_threshold_pct, description, status,
                created_at, updated_at
            ) VALUES (
                v_company_id, 'JE', 'JE',
                1, 999999, v_max_entry,
                80, 'Comprobante contable general (default)', 'ACTIVE',
                NOW(), NOW()
            );
            RAISE NOTICE 'V9-ZZO: Serie JE default creada para empresa %, current_number=%',
                         v_company_id, v_max_entry;
        END IF;
    END LOOP;
END $$;
