-- Sprint Final: cobertura permisos legacy (PERM_VERB_NOUN) que aun viven
-- en @PreAuthorize de muchos controllers. Inserta los codes faltantes y los
-- asigna a los 3 roles operativos para que CONTADOR/AUDITOR/ADMIN puedan
-- usar los endpoints sin paridad con glosario nuevo.
DO $$
DECLARE
    v_role_admin INT;
    v_role_contador INT;
    v_role_auditor INT;
    v_module_id INT;
    v_perm_id INT;
    legacy_code TEXT;
    legacy_codes TEXT[] := ARRAY[
        'ADJUST_ECL_SEGMENT','APPROVE_PURCHASE_ORDER','ASSIGN_ACCOUNTING_ACCOUNT_TO_RULER_TAX',
        'ASSIGN_ROLE','BULK_STORE_THIRD_PARTY','CALCULATE_ECL_SEGMENT','CHANGE_CASH_STATUS',
        'CREATE_ACCOUNTING_ACCOUNT','CREATE_AP_ADVANCE','CREATE_AP_NOTE','CREATE_AP_PAYMENT',
        'CREATE_AR_ADVANCE','CREATE_AR_NOTE','CREATE_AR_PAYMENT','CREATE_ASSET','CREATE_CASH',
        'CREATE_CHART_OF_ACCOUNT','CREATE_COMMERCIAL_DATA','CREATE_COST_CENTER','CREATE_COUNTRY',
        'CREATE_CURRENCY_TYPE','CREATE_DEPRECIATION_RULE','CREATE_DEPRETATION_RULE',
        'CREATE_DIAN_RESOLUTION','CREATE_DIAN_XML','CREATE_EXCHANGE_RATES','CREATE_GOODS_RECEIPT',
        'CREATE_INVOICE_ATTACHMENT','CREATE_JOURNAL_ENTRY','CREATE_MENU','CREATE_MENU_PERMISSION',
        'CREATE_MODULE','CREATE_MUNICIPALITY','CREATE_PARAMETER','CREATE_PERMISSION',
        'CREATE_PURCHASE_ORDER','CREATE_REPORT_TEMPLATE','CREATE_REPORT_TYPE','CREATE_RULER_TAX',
        'CREATE_ROLE','CREATE_SALES_INVOICE','CREATE_SUPPLIER_INVOICE','CREATE_THIRD_PARTY',
        'CREATE_USER','CREATE_VOUCHER','CREATE_WITHHOLDING','CREATE_WITHHOLDING_ASSIGNMENT',
        'DELETE_ACCOUNTING_ACCOUNT','DELETE_ASSET','DELETE_CASH','DELETE_CHART_OF_ACCOUNT',
        'DELETE_COMMERCIAL_DATA','DELETE_COST_CENTER','DELETE_COUNTRY','DELETE_CURRENCY_TYPE',
        'DELETE_DEPRECIATION_RULE','DELETE_DEPRETATION_RULE','DELETE_DIAN_RESOLUTION',
        'DELETE_EXCHANGE_RATES','DELETE_INVOICE_ATTACHMENT','DELETE_JOURNAL_ENTRY','DELETE_MENU',
        'DELETE_MENU_PERMISSION','DELETE_MODULE','DELETE_MUNICIPALITY','DELETE_PARAMETER',
        'DELETE_PERMISSION','DELETE_REPORT_TEMPLATE','DELETE_REPORT_TYPE','DELETE_ROLE',
        'DELETE_RULER_TAX','DELETE_THIRD_PARTY','DELETE_USER','DELETE_VOUCHER',
        'DELETE_WITHHOLDING','DELETE_WITHHOLDING_ASSIGNMENT','EXPORT_AUDIT_LOGS',
        'EXPORT_THIRD_PARTY','GENERATE_DEPRECIATION','LINK_GOODS_RECEIPT_TO_INVOICE',
        'POST_JOURNAL_ENTRY','REJECT_GOODS_RECEIPT','REJECT_PURCHASE_ORDER','REVERSE_JOURNAL_ENTRY',
        'SEARCH_AUDIT_LOG','SEARCH_THIRD_PARTY','SEARCH_VOUCHER','SUBMIT_DIAN','UPDATE_ACCOUNTING_ACCOUNT',
        'UPDATE_AP_PAYMENT','UPDATE_ASSET','UPDATE_CASH','UPDATE_CHART_OF_ACCOUNT',
        'UPDATE_COMMERCIAL_DATA','UPDATE_COST_CENTER','UPDATE_COUNTRY','UPDATE_CURRENCY_TYPE',
        'UPDATE_DEPRECIATION_RULE','UPDATE_DEPRETATION_RULE','UPDATE_DIAN_RESOLUTION',
        'UPDATE_EXCHANGE_RATES','UPDATE_JOURNAL_ENTRY','UPDATE_MENU','UPDATE_MODULE',
        'UPDATE_MUNICIPALITY','UPDATE_PARAMETER','UPDATE_PERMISSION','UPDATE_REPORT_TYPE',
        'UPDATE_ROLE','UPDATE_RULER_TAX','UPDATE_SALES_INVOICE','UPDATE_THIRD_PARTY',
        'UPDATE_USER','UPDATE_VOUCHER','UPDATE_WITHHOLDING','UPDATE_WITHHOLDING_ASSIGNMENT',
        'VIEW_ACCOUNTING_ACCOUNT','VIEW_AP_INVOICE','VIEW_AR_INVOICE','VIEW_ASSET',
        'VIEW_AUDIT_LOG','VIEW_BANK','VIEW_BANK_ACCOUNT','VIEW_BANK_BRANCH','VIEW_CASH',
        'VIEW_CHART_OF_ACCOUNT','VIEW_CHECK','VIEW_CHECKBOOK','VIEW_COMMERCIAL_DATA',
        'VIEW_COST_CENTER','VIEW_COUNTRIES','VIEW_COUNTRY','VIEW_CURRENCY_TYPE',
        'VIEW_DEPRETATION_RULE','VIEW_DEPRECIATION_RULE','VIEW_DIAN_RESOLUTION',
        'VIEW_EXCHANGE_RATES','VIEW_GOODS_RECEIPT','VIEW_INVOICE_ATTACHMENT','VIEW_JOURNAL_ENTRY',
        'VIEW_MENU','VIEW_MENU_PERMISSION','VIEW_MODULE','VIEW_MODULES_MENU','VIEW_MUNICIPALITY',
        'VIEW_PARAMETER','VIEW_PERMISSION','VIEW_PURCHASE_ORDER','VIEW_REPORT_TEMPLATE',
        'VIEW_REPORT_TYPE','VIEW_ROLE','VIEW_RULER_TAX','VIEW_THIRD_PARTY','VIEW_USER',
        'VIEW_VOUCHER','VIEW_WITHHOLDING','VIEW_WITHHOLDING_ASSIGNMENT'
    ];
BEGIN
    SELECT id INTO v_role_admin FROM roles WHERE name='ADMIN_EMPRESA' AND deleted_at IS NULL LIMIT 1;
    SELECT id INTO v_role_contador FROM roles WHERE name='CONTADOR' AND deleted_at IS NULL LIMIT 1;
    SELECT id INTO v_role_auditor FROM roles WHERE name='AUDITOR' AND deleted_at IS NULL LIMIT 1;
    -- Modulo PA por defecto (cualquier modulo, NOT NULL en permissions)
    SELECT id INTO v_module_id FROM modules WHERE deleted_at IS NULL ORDER BY id LIMIT 1;

    FOREACH legacy_code IN ARRAY legacy_codes LOOP
        -- Insertar permiso si no existe
        SELECT id INTO v_perm_id FROM permissions WHERE code = legacy_code AND deleted_at IS NULL LIMIT 1;
        IF v_perm_id IS NULL THEN
            INSERT INTO permissions (code, name, description, type, module_id, created_at, updated_at)
            VALUES (legacy_code, legacy_code || ' (legacy)', 'Legacy code from Sprint Final',
                    CASE WHEN legacy_code LIKE 'CREATE_%' THEN 'CREATE'
                         WHEN legacy_code LIKE 'UPDATE_%' THEN 'UPDATE'
                         WHEN legacy_code LIKE 'DELETE_%' THEN 'DELETE'
                         ELSE 'READ' END,
                    v_module_id, NOW(), NOW())
            RETURNING id INTO v_perm_id;
        END IF;

        -- ADMIN_EMPRESA: TODOS
        IF v_role_admin IS NOT NULL THEN
            INSERT INTO roles_permissions (role_id, permission_id)
            VALUES (v_role_admin, v_perm_id)
            ON CONFLICT DO NOTHING;
        END IF;

        -- CONTADOR: TODOS los operativos (excepto PERMISSION/USER/ROLE/MENU/MODULE admin)
        IF v_role_contador IS NOT NULL AND legacy_code NOT IN (
            'CREATE_PERMISSION','UPDATE_PERMISSION','DELETE_PERMISSION',
            'CREATE_ROLE','UPDATE_ROLE','DELETE_ROLE','ASSIGN_ROLE',
            'CREATE_USER','UPDATE_USER','DELETE_USER',
            'CREATE_MENU','UPDATE_MENU','DELETE_MENU','CREATE_MENU_PERMISSION','DELETE_MENU_PERMISSION',
            'CREATE_MODULE','UPDATE_MODULE','DELETE_MODULE'
        ) THEN
            INSERT INTO roles_permissions (role_id, permission_id)
            VALUES (v_role_contador, v_perm_id)
            ON CONFLICT DO NOTHING;
        END IF;

        -- AUDITOR: solo VIEW_* y SEARCH_* y EXPORT_*
        IF v_role_auditor IS NOT NULL AND (
            legacy_code LIKE 'VIEW_%' OR legacy_code LIKE 'SEARCH_%' OR legacy_code LIKE 'EXPORT_%'
        ) THEN
            INSERT INTO roles_permissions (role_id, permission_id)
            VALUES (v_role_auditor, v_perm_id)
            ON CONFLICT DO NOTHING;
        END IF;
    END LOOP;

    RAISE NOTICE 'V9-ZZZF: legacy codes mapeados a roles operativos';
END
$$;
