-- =============================================================================
-- V9-ZZN__journal_entry_supports.sql
--
-- HU-CG-05A/B/C (Bloque X): comprobantes (PDF/JPG/PNG) adjuntos a asientos
-- contables. Estructura paralela a sales_invoice_attachments (AR-03) — el
-- patron ya esta validado y se replica en CG.
--
-- Multi-tenant: company_id NOT NULL + UNIQUE NO global (cada empresa gestiona
-- sus propios soportes). Soft-delete preserva auditoria.
--
-- Idempotente: CREATE TABLE IF NOT EXISTS + CREATE INDEX IF NOT EXISTS.
-- Hibernate ddl-auto=update tambien crea esta tabla automaticamente desde la
-- entidad JournalEntrySupport, pero la creamos via migracion para asegurar
-- los indices y poder hacer backfill defensivo si alguna empresa de QA
-- tuviera datos historicos.
-- =============================================================================

CREATE TABLE IF NOT EXISTS journal_entry_supports (
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id        BIGINT NOT NULL,
    journal_entry_id  BIGINT NOT NULL,
    file_name         VARCHAR(255) NOT NULL,
    mime_type         VARCHAR(100) NOT NULL,
    file_size         BIGINT NOT NULL,
    file_content      BYTEA NOT NULL,
    support_type      VARCHAR(50),
    description       VARCHAR(500),
    uploaded_by       VARCHAR(150),
    uploaded_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMP NULL,
    CONSTRAINT fk_jes_journal_entry FOREIGN KEY (journal_entry_id)
        REFERENCES journal_entries(id) ON DELETE RESTRICT
);

-- Indices para queries comunes:
-- 1) listar soportes vigentes de un asiento (FROM by journal_entry_id)
CREATE INDEX IF NOT EXISTS idx_jes_je_active
    ON journal_entry_supports (journal_entry_id, deleted_at);

-- 2) filtrar por tenant (multi-tenant filter)
CREATE INDEX IF NOT EXISTS idx_jes_company
    ON journal_entry_supports (company_id);

-- 3) busquedas administrativas por tipo
CREATE INDEX IF NOT EXISTS idx_jes_support_type
    ON journal_entry_supports (support_type) WHERE deleted_at IS NULL;
